# yaml-language-server: $schema=https://taskfile.dev/schema.json

#####################################################################
# Docs: https://taskfile.dev                                        #
#                                                                   #
# Use npx with the "--no" argument to ensure that dependencies with #
# versions different from those in package.json are not downloaded. #
#####################################################################

version: "3"

vars:
  VERSION:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: >-
    -s -w
    -X github.com/varavelio/nsqlite/internal/version.Version={{.VERSION}}
    -X github.com/varavelio/nsqlite/internal/version.Commit={{.COMMIT}}
    -X github.com/varavelio/nsqlite/internal/version.Date={{.DATE}}

tasks:
  ci:
    desc: Run all CI checks
    cmds:
      - task: deps
      - task: format
      - task: lint
      - task: test
      - task: build

  deps:
    desc: Install all dependencies
    cmds:
      - go mod download
      - go run ./scripts/fetch-sqlite/main.go
      - npm install

  build:
    desc: Build the binary for the current platform
    deps:
      - codegen
    cmd: mkdir -p ./dist && CGO_ENABLED=1 go build -trimpath -ldflags "{{.LDFLAGS}}" -o ./dist/nsqlite ./cmd/nsqlite

  build:entrypoint:
    desc: Build the container entrypoint binary for the current platform
    cmd: mkdir -p ./dist && CGO_ENABLED=0 go build -trimpath -ldflags "{{.LDFLAGS}}" -o ./dist/entrypoint ./cmd/entrypoint

  run:
    desc: Run the project (blocking)
    deps:
      - build
    cmd: ./dist/nsqlite

  codegen:
    desc: Run code generators
    cmd: vdl generate ./schema/vdl.config.vdl

  format:
    desc: Format all code
    cmds:
      - npx --no dprint fmt --config ./dprint.json --log-level warn
      - golangci-lint fmt ./...

  lint:
    desc: Lint all code
    cmds:
      - npx --no dprint check --config ./dprint.json --log-level warn
      - golangci-lint run ./...

  test:
    desc: Test all code
    cmds:
      - go test ./...
      - go test -race ./...
