# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build the distributable binaries for all platforms
    cmds:
      - rm -rf ./dist
      - chmod +x ./build.ts
      - ./build.ts

  install:
    desc: Build and install binaries locally for development
    cmds:
      - go install ./cmd/nsqlite/.
      - go install ./cmd/nsqlited/.
      - go install ./cmd/nsqlitebench/.

  run:cli:
    desc: Build and run NSQLite CLI locally
    deps: [build:cli]
    cmd: ./dist/nsqlite {{.CLI_ARGS}}

  build:cli:
    desc: Build NSQLite CLI locally
    cmd: go build -o ./dist/nsqlite ./cmd/nsqlite/.

  run:server:
    desc: Build and run NSQLite Server locally
    deps: [build:server]
    cmd: ./dist/nsqlited {{.CLI_ARGS}}

  build:server:
    desc: Build NSQLite Server locally
    cmd: go build -o ./dist/nsqlited ./cmd/nsqlited/.

  run:bench:
    desc: Build and run NSQLite Benchmark locally
    deps: [build:bench]
    cmd: ./dist/nsqlitebench {{.CLI_ARGS}}

  build:bench:
    desc: Build NSQLite Benchmark locally
    cmd: go build -o ./dist/nsqlitebench ./cmd/nsqlitebench/.

  fmt:
    desc: Format the Go, Js and Ts code
    cmds:
      - go fmt ./...
      - deno fmt ./

  lint:
    desc: Run linter for Go, Js and Ts code
    cmds:
      - golangci-lint run ./...
      - deno lint ./

  test:
    desc: Run tests for Go
    cmds:
      - go test -v ./...
