// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-rpc-go@v0.1.2 (hash da31800b)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

package vdl

import (
	"context"
	"fmt"
	json "github.com/goccy/go-json"
	"io"
	"net/http"
	"sync"
	"time"
)

// -----------------------------------------------------------------------------
// RPC Catalog
// -----------------------------------------------------------------------------

// VDLPaths contains the generated path catalog for every procedure and stream.
var VDLPaths = struct {
	Database struct {
		Query string
	}
	System struct {
		Health  string
		Session string
		Status  string
	}
}{
	Database: struct {
		Query string
	}{
		Query: "/Database/query",
	},
	System: struct {
		Health  string
		Session string
		Status  string
	}{
		Health:  "/System/health",
		Session: "/System/session",
		Status:  "/System/status",
	},
}

// VDLProcedures contains every generated procedure definition.
var VDLProcedures = []OperationDefinition{
	{
		RPCName:     "Database",
		Name:        "query",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
	{
		RPCName:     "System",
		Name:        "health",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
	{
		RPCName:     "System",
		Name:        "session",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
	{
		RPCName:     "System",
		Name:        "status",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
}

// VDLStreams contains every generated stream definition.
var VDLStreams = []OperationDefinition{}

// -----------------------------------------------------------------------------
// RPC Core Types
// -----------------------------------------------------------------------------

// OperationType identifies the transport behavior of an RPC operation and can
// be proc or stream.
type OperationType string

const (
	// OperationTypeProc identifies a request-response procedure.
	OperationTypeProc OperationType = "proc"
	// OperationTypeStream identifies a Server-Sent Events stream.
	OperationTypeStream OperationType = "stream"
)

// Annotation represents operation-level annotation metadata preserved from VDL.
type Annotation struct {
	// Name is the annotation identifier without the @ prefix.
	Name string
	// Argument contains the resolved annotation payload when one was declared.
	Argument any
}

// OperationDefinition describes a generated procedure or stream.
type OperationDefinition struct {
	// RPCName is the VDL service name that owns the operation.
	RPCName string
	// Name is the VDL field name of the operation.
	Name string
	// Type indicates whether the operation is a procedure or a stream.
	Type OperationType
	// Annotations contains every non-marker annotation declared on the operation.
	Annotations []Annotation
}

// Path returns the transport path used by the generated client and server.
func (o OperationDefinition) Path() string {
	return "/" + o.RPCName + "/" + o.Name
}

// cloneAnnotations returns a shallow copy of the given annotations slice.
func cloneAnnotations(annotations []Annotation) []Annotation {
	if len(annotations) == 0 {
		return nil
	}
	clone := make([]Annotation, len(annotations))
	copy(clone, annotations)
	return clone
}

// Void represents the absence of an input or output payload.
type Void struct{}

// Response represents the response of a VDL call.
type Response[T any] struct {
	Ok     bool  `json:"ok"`
	Output T     `json:"output,omitempty,omitzero"`
	Error  Error `json:"error,omitzero"`
}

// Write writes the response as JSON to the provided writer.
func (r Response[T]) Write(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

// String returns the response as a JSON string.
func (r Response[T]) String() string {
	encoded, err := json.Marshal(r)
	if err != nil {
		return fmt.Sprintf(`{"ok":false,"error":{"message":%q}}`, "failed to marshal response: "+err.Error())
	}
	return string(encoded)
}

// Bytes returns the response as a JSON byte slice.
func (r Response[T]) Bytes() []byte {
	return []byte(r.String())
}

// Error represents a standardized error in the VDL system.
//
// It provides structured information about errors that occur within the system,
// enabling consistent error handling across servers and clients.
//
// Fields:
//   - Message: A human-readable description of the error.
//   - Category: Optional. Categorizes the error by its nature or source (e.g., "ValidationError", "DatabaseError").
//   - Code: Optional. A machine-readable identifier for the specific error condition (e.g., "INVALID_EMAIL").
//   - Details: Optional. Additional information about the error.
//
// The struct implements the error interface.
type Error struct {
	// Message provides a human-readable description of the error.
	//
	// This message can be displayed to end-users or used for logging and debugging purposes.
	//
	// Use Cases:
	//   1. Message can be directly shown to the user to inform them of the issue.
	//   2. Developers can use Message in logs to diagnose problems during development or in production.
	Message string `json:"message"`
	// Category categorizes the error by its nature or source.
	//
	// Examples:
	//   - "ValidationError" for input validation errors.
	//   - "DatabaseError" for errors originating from database operations.
	//   - "AuthenticationError" for authentication-related issues.
	//
	// Use Cases:
	//   1. In middleware, you can use Category to determine how to handle the error.
	//      For instance, you might log "InternalError" types and return a generic message to the client.
	//   2. Clients can inspect the Category to decide whether to prompt the user for action,
	//      such as re-authentication if the Category is "AuthenticationError".
	Category string `json:"category,omitzero"`
	// Code is a machine-readable identifier for the specific error condition.
	//
	// Examples:
	//   - "INVALID_EMAIL" when an email address fails validation.
	//   - "USER_NOT_FOUND" when a requested user does not exist.
	//   - "RATE_LIMIT_EXCEEDED" when a client has made too many requests.
	//
	// Use Cases:
	//   1. Clients can map Codes to localized error messages for internationalization (i18n),
	//      displaying appropriate messages based on the user's language settings.
	//   2. Clients or middleware can implement specific logic based on the Code,
	//      such as retry mechanisms for "TEMPORARY_FAILURE" or showing captcha for "RATE_LIMIT_EXCEEDED".
	Code string `json:"code,omitzero"`
	// Details contains optional additional information about the error.
	//
	// This field can include any relevant data that provides more context about the error.
	// The contents should be serializable to JSON.
	//
	// Use Cases:
	//   1. Providing field-level validation errors, e.g., Details could be:
	//      {"fields": {"email": "Email is invalid", "password": "Password is too short"}}
	//   2. Including diagnostic information such as timestamps, request IDs, or stack traces
	//      (ensure sensitive information is not exposed to clients).
	Details map[string]any `json:"details,omitempty"`
}

// Error implements the standard error interface.
func (e Error) Error() string {
	return e.Message
}

// String implements fmt.Stringer.
func (e Error) String() string {
	return e.Message
}

// Is reports whether the target error matches this error.
//
// It checks if the target is of type Error (or *Error) and compares
// their Code and Message fields.
//
// Matching Logic:
//  1. If both errors have a Code, they match if the Codes are identical.
//  2. If one or both lack a Code, they match if the Messages are identical.
//  3. Details and Category are ignored for comparison to avoid issues with non-comparable map types.
func (e Error) Is(target error) bool {
	var t Error
	switch err := target.(type) {
	case Error:
		t = err
	case *Error:
		t = *err
	default:
		return false
	}
	if e.Code != "" && t.Code != "" {
		return e.Code == t.Code
	}
	return e.Message == t.Message
}

// ToJSON returns the Error as a JSON-formatted string including all its fields.
// This is useful for logging and debugging purposes.
func (e Error) ToJSON() string {
	b, err := json.Marshal(e)
	if err != nil {
		return fmt.Sprintf(
			`{"message":%q,"details":{"message":%q}}`,
			"failed to marshal VDL Error: "+err.Error(), e.Message,
		)
	}
	return string(b)
}

// ToError converts any error into an Error.
//
// If the provided error is already a Error, it returns it as is.
// Otherwise, it wraps the error message into a new Error.
//
// This function ensures that all errors conform to the Error structure,
// facilitating consistent error handling across the system.
func ToError(err error) Error {
	switch e := err.(type) {
	case Error:
		return e
	case *Error:
		return *e
	default:
		return Error{
			Message: err.Error(),
		}
	}
}

// -----------------------------------------------------------------------------
// Server Types
// -----------------------------------------------------------------------------

// HTTPAdapter defines the interface required by VDL server to handle
// incoming HTTP requests and write responses to clients. This abstraction allows
// the server to work with different HTTP frameworks while maintaining the same
// core functionality.
//
// Implementations must provide methods to read request bodies, set response headers,
// write response data, and flush the response buffer to ensure immediate delivery
// to the client.
type HTTPAdapter interface {
	// RequestBody returns the body reader for the incoming HTTP request.
	// The returned io.Reader allows the server to read the request payload
	// containing RPC call data.
	RequestBody() io.Reader
	// SetHeader sets a response header with the specified key-value pair.
	// This is used to configure response headers like Content-Type and
	// caching directives for both procedure and stream responses.
	SetHeader(key, value string)
	// Write writes the provided data to the response body.
	// Returns the number of bytes written and any error encountered.
	// For procedures, this writes the complete JSON response. For streams,
	// this writes individual Server-Sent Events data chunks.
	Write(data []byte) (int, error)
	// Flush immediately sends any buffered response data to the client.
	// This is crucial for streaming responses to ensure real-time delivery
	// of events. Returns an error if the flush operation fails.
	Flush() error
}

// NetHTTPAdapter implements HTTPAdapter for Go's standard net/http package.
// This adapter bridges the VDL server with the standard HTTP library, allowing
// seamless integration with existing HTTP servers and middlewares.
type NetHTTPAdapter struct {
	responseWriter http.ResponseWriter
	request        *http.Request
}

// NewNetHTTPAdapter creates a new NetHTTPAdapter that implements the
// HTTPAdapter interface for net/http.
//
// Parameters:
//   - w: The http.ResponseWriter to write responses to
//   - r: The *http.Request containing the incoming request data
//
// Returns a HTTPAdapter implementation ready for use with VDL server.
func NewNetHTTPAdapter(w http.ResponseWriter, r *http.Request) HTTPAdapter {
	return &NetHTTPAdapter{
		responseWriter: w,
		request:        r,
	}
}

// RequestBody returns the body reader for the HTTP request.
// This provides access to the request payload containing the RPC call data.
func (r *NetHTTPAdapter) RequestBody() io.Reader {
	return r.request.Body
}

// SetHeader sets a response header with the specified key-value pair.
// This configures headers for the HTTP response, such as Content-Type
// for JSON responses or streaming-specific headers.
func (r *NetHTTPAdapter) SetHeader(key, value string) {
	r.responseWriter.Header().Set(key, value)
}

// Write writes the provided data to the HTTP response body.
// Returns the number of bytes written and any error encountered during writing.
func (r *NetHTTPAdapter) Write(data []byte) (int, error) {
	return r.responseWriter.Write(data)
}

// Flush immediately sends any buffered response data to the client.
// For streaming responses, this ensures real-time delivery of events.
// If the underlying ResponseWriter doesn't support flushing, this is a no-op.
func (r *NetHTTPAdapter) Flush() error {
	if f, ok := r.responseWriter.(http.Flusher); ok {
		f.Flush()
	}
	return nil
}

// -----------------------------------------------------------------------------
// Middleware-based Server Architecture
// -----------------------------------------------------------------------------

// HandlerContext is the unified container for all request information and state
// that flows through the entire request processing pipeline.
//
// The generic type P represents the user-defined container for application
// dependencies and request data (e.g., UserID, DB connection, etc.).
//
// The generic type I represents the input type, which can be any type depending
// on the operation.
//
//   - T: The type of the Props field, which is a user-defined container for application and request data.
//   - I: The type of the Input field, which contains the deserialized request body. For global middlewares, this will be any.
type HandlerContext[T any, I any] struct {
	// Props is the user-defined container, created per request,
	// for application dependencies and request data (e.g., UserID).
	Props T
	// Input contains the request body, already deserialized and typed.
	// For global middlewares, the type I will be any.
	Input I
	// Context is the standard Go context.Context for cancellations and deadlines.
	Context context.Context
	// Annotations is a slice of annotation objects associated with the request.
	Annotations []Annotation
	// operation is the details of the RPC operation including it's RPC name, operation name and type.
	operation OperationDefinition
}

// RPCName returns the name of the RPC service
func (h *HandlerContext[T, I]) RPCName() string { return h.operation.RPCName }

// OperationName returns the name of the operation (e.g. "CreateUser", "GetPost", etc.)
func (h *HandlerContext[T, I]) OperationName() string { return h.operation.Name }

// OperationType returns the type of operation, can be [OperationTypeProc] ("proc") or [OperationTypeStream] ("stream")
func (h *HandlerContext[T, I]) OperationType() OperationType { return h.operation.Type }

// GlobalHandlerFunc is the signature for a global handler function for procedures and streams.
//
//   - T: Application-defined context type (props).
type GlobalHandlerFunc[T any] func(c *HandlerContext[T, any]) (any, error)

// GlobalMiddlewareFunc is the signature for a middleware applied to all requests.
//
//   - T: Application-defined context type (props).
type GlobalMiddlewareFunc[T any] func(next GlobalHandlerFunc[T]) GlobalHandlerFunc[T]

// ProcHandlerFunc is the signature of the final business handler for a proc.
//
//   - T: Application-defined context type (props).
//   - I: Input payload type for the procedure.
//   - O: Output payload type for the procedure.
type ProcHandlerFunc[T any, I any, O any] func(c *HandlerContext[T, I]) (O, error)

// ProcMiddlewareFunc is the signature for a proc-specific typed middleware.
// It uses a wrapper pattern for a clean composition.
//
// This is the same as [GlobalMiddlewareFunc] but for specific procedures and with types.
//
//   - T: Application-defined context type (props).
//   - I: Input payload type for the procedure.
//   - O: Output payload type for the procedure.
type ProcMiddlewareFunc[T any, I any, O any] func(next ProcHandlerFunc[T, I, O]) ProcHandlerFunc[T, I, O]

// StreamHandlerFunc is the signature of the main handler that initializes a stream.
//
//   - T: Application-defined context type (props).
//   - I: Input payload type for the stream (subscription parameters).
//   - O: Output payload type for the stream (event data).
type StreamHandlerFunc[T any, I any, O any] func(c *HandlerContext[T, I], emit EmitFunc[T, I, O]) error

// StreamMiddlewareFunc is the signature for a middleware that wraps the main stream handler.
//
//   - T: Application-defined context type (props).
//   - I: Input payload type for the stream.
//   - O: Output payload type for the stream.
type StreamMiddlewareFunc[T any, I any, O any] func(next StreamHandlerFunc[T, I, O]) StreamHandlerFunc[T, I, O]

// EmitFunc is the signature for emitting events from a stream.
//
//   - T: Application-defined context type (props).
//   - I: Input payload type for the stream.
//   - O: Output payload type for the stream.
type EmitFunc[T any, I any, O any] func(c *HandlerContext[T, I], output O) error

// EmitMiddlewareFunc is the signature for a middleware that wraps each call to emit.
//
//   - T: Application-defined context type (props).
//   - I: Input payload type for the stream.
//   - O: Output payload type for the stream.
type EmitMiddlewareFunc[T any, I any, O any] func(next EmitFunc[T, I, O]) EmitFunc[T, I, O]

// DeserializerFunc function convert raw JSON input into typed input prior to handler execution.
type DeserializerFunc func(raw json.RawMessage) (any, error)

// ErrorHandlerFunc transforms an internal Go error into a public VDL Error.
//
// The handler receives the full request context, enabling structured logging
// with access to Props, RPC Name, Operation Name, and other metadata.
//
//   - T: Application-defined context type (props).
type ErrorHandlerFunc[T any] func(c *HandlerContext[T, any], err error) Error

// StreamConfig allows configuring the behavior of streams.
type StreamConfig struct {
	// PingInterval is the interval at which ping events are sent to the client
	// to keep the connection alive. Defaults to 30 seconds.
	PingInterval time.Duration
}

// -----------------------------------------------------------------------------
// Internal Server Implementation
// -----------------------------------------------------------------------------

// internalServer manages RPC request handling and middleware execution for
// both procedures and streams. It maintains handler registrations, middleware
// chains, and coordinates the complete request lifecycle.
//
// The generic type P represents the user context type, allowing users to pass
// custom data (authentication info, user sessions, etc.) through the entire
// request processing pipeline.
//
//   - T: Application-defined context type (props).
type internalServer[T any] struct {
	// handlersMu protects all handler maps and middleware slices from concurrent access
	handlersMu sync.RWMutex

	// operationDefs contains the definition of all registered operations.
	// Map format: rpcName -> operationName -> OperationDefinition.
	operationDefs map[string]map[string]OperationDefinition

	// procHandlers stores the final implementation functions for procedures
	// Map format: rpcName -> procName -> handler
	procHandlers map[string]map[string]ProcHandlerFunc[T, any, any]

	// streamHandlers stores the final implementation functions for streams
	// Map format: rpcName -> streamName -> handler
	streamHandlers map[string]map[string]StreamHandlerFunc[T, any, any]

	// globalMiddlewares contains middlewares that run for every request (both procs and streams)
	globalMiddlewares []GlobalMiddlewareFunc[T]

	// rpcMiddlewares contains middlewares that run for every request within a specific RPC
	// Map format: rpcName -> middlewares
	rpcMiddlewares map[string][]GlobalMiddlewareFunc[T]

	// procMiddlewares contains per-procedure middlewares
	// Map format: rpcName -> procName -> middlewares
	procMiddlewares map[string]map[string][]ProcMiddlewareFunc[T, any, any]

	// streamMiddlewares contains per-stream middlewares
	// Map format: rpcName -> streamName -> middlewares
	streamMiddlewares map[string]map[string][]StreamMiddlewareFunc[T, any, any]

	// streamEmitMiddlewares contains per-stream emit middlewares
	// Map format: rpcName -> streamName -> middlewares
	streamEmitMiddlewares map[string]map[string][]EmitMiddlewareFunc[T, any, any]

	// procDeserializers contains per-procedure input deserializers
	// Map format: rpcName -> procName -> deserializer
	procDeserializers map[string]map[string]DeserializerFunc

	// streamDeserializers contains per-stream input deserializers
	// Map format: rpcName -> streamName -> deserializer
	streamDeserializers map[string]map[string]DeserializerFunc

	// globalStreamConfig contains the global configuration for streams
	globalStreamConfig StreamConfig

	// rpcStreamConfigs contains per-RPC configuration for streams
	// Map format: rpcName -> config
	rpcStreamConfigs map[string]StreamConfig

	// streamConfigs contains per-stream configuration
	// Map format: rpcName -> streamName -> config
	streamConfigs map[string]map[string]StreamConfig

	// globalErrorHandler is the global error handler
	globalErrorHandler ErrorHandlerFunc[T]

	// rpcErrorHandlers contains per-RPC error handlers
	// Map format: rpcName -> handler
	rpcErrorHandlers map[string]ErrorHandlerFunc[T]
}

// newInternalServer creates a new VDL server instance with the specified
// procedure and stream definitions. The server is initialized with empty handler
// maps and middleware slices, ready for registration.
//
// The generic type T represents the user context type, used to pass additional
// data to handlers, such as authentication information, user sessions, or any
// other request-scoped data.
//
// Parameters:
//   - procDefs: List of procedure definitions that this server will handle
//   - streamDefs: List of stream definitions that this server will handle
//   - T: Application-defined context type (props).
//
// Returns a new internalServer instance ready for handler and middleware registration.
func newInternalServer[T any](procDefs []OperationDefinition, streamDefs []OperationDefinition) *internalServer[T] {
	// Initialize maps
	operationDefs := make(map[string]map[string]OperationDefinition)
	procHandlers := make(map[string]map[string]ProcHandlerFunc[T, any, any])
	streamHandlers := make(map[string]map[string]StreamHandlerFunc[T, any, any])
	rpcMiddlewares := make(map[string][]GlobalMiddlewareFunc[T])
	procMiddlewares := make(map[string]map[string][]ProcMiddlewareFunc[T, any, any])
	streamMiddlewares := make(map[string]map[string][]StreamMiddlewareFunc[T, any, any])
	streamEmitMiddlewares := make(map[string]map[string][]EmitMiddlewareFunc[T, any, any])
	procDeserializers := make(map[string]map[string]DeserializerFunc)
	streamDeserializers := make(map[string]map[string]DeserializerFunc)
	rpcStreamConfigs := make(map[string]StreamConfig)
	streamConfigs := make(map[string]map[string]StreamConfig)
	rpcErrorHandlers := make(map[string]ErrorHandlerFunc[T])

	// Helper to ensure RPC map existence
	ensureRPC := func(rpcName string) {
		if _, ok := operationDefs[rpcName]; !ok {
			operationDefs[rpcName] = make(map[string]OperationDefinition)
			procHandlers[rpcName] = make(map[string]ProcHandlerFunc[T, any, any])
			streamHandlers[rpcName] = make(map[string]StreamHandlerFunc[T, any, any])
			procMiddlewares[rpcName] = make(map[string][]ProcMiddlewareFunc[T, any, any])
			streamMiddlewares[rpcName] = make(map[string][]StreamMiddlewareFunc[T, any, any])
			streamEmitMiddlewares[rpcName] = make(map[string][]EmitMiddlewareFunc[T, any, any])
			procDeserializers[rpcName] = make(map[string]DeserializerFunc)
			streamDeserializers[rpcName] = make(map[string]DeserializerFunc)
			streamConfigs[rpcName] = make(map[string]StreamConfig)
		}
	}

	for _, def := range procDefs {
		ensureRPC(def.RPCName)
		operationDefs[def.RPCName][def.Name] = def
	}
	for _, def := range streamDefs {
		ensureRPC(def.RPCName)
		operationDefs[def.RPCName][def.Name] = def
	}

	return &internalServer[T]{
		handlersMu:            sync.RWMutex{},
		operationDefs:         operationDefs,
		procHandlers:          procHandlers,
		streamHandlers:        streamHandlers,
		globalMiddlewares:     []GlobalMiddlewareFunc[T]{},
		rpcMiddlewares:        rpcMiddlewares,
		procMiddlewares:       procMiddlewares,
		streamMiddlewares:     streamMiddlewares,
		streamEmitMiddlewares: streamEmitMiddlewares,
		procDeserializers:     procDeserializers,
		streamDeserializers:   streamDeserializers,
		globalStreamConfig:    StreamConfig{PingInterval: 30 * time.Second},
		rpcStreamConfigs:      rpcStreamConfigs,
		streamConfigs:         streamConfigs,
		globalErrorHandler:    nil,
		rpcErrorHandlers:      rpcErrorHandlers,
	}
}

// addGlobalMiddleware registers a global middleware that executes for every request (proc and stream).
// Middlewares are executed in the order they were registered.
func (s *internalServer[T]) addGlobalMiddleware(
	mw GlobalMiddlewareFunc[T],
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.globalMiddlewares = append(s.globalMiddlewares, mw)
	return s
}

// addRPCMiddleware registers a middleware that executes for every request within a specific RPC.
// Middlewares are executed in the order they were registered.
func (s *internalServer[T]) addRPCMiddleware(
	rpcName string,
	mw GlobalMiddlewareFunc[T],
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.rpcMiddlewares[rpcName] = append(s.rpcMiddlewares[rpcName], mw)
	return s
}

// addProcMiddleware registers a wrapper middleware for a specific procedure.
// Middlewares are executed in the order they were registered.
func (s *internalServer[T]) addProcMiddleware(
	rpcName string,
	procName string,
	mw ProcMiddlewareFunc[T, any, any],
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.procMiddlewares[rpcName][procName] = append(s.procMiddlewares[rpcName][procName], mw)
	return s
}

// addStreamMiddleware registers a wrapper middleware for a specific stream.
// Middlewares are executed in the order they were registered.
func (s *internalServer[T]) addStreamMiddleware(
	rpcName string,
	streamName string,
	mw StreamMiddlewareFunc[T, any, any],
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.streamMiddlewares[rpcName][streamName] = append(s.streamMiddlewares[rpcName][streamName], mw)
	return s
}

// addStreamEmitMiddleware registers an emit wrapper middleware for a specific stream.
// Middlewares are executed in the order they were registered.
func (s *internalServer[T]) addStreamEmitMiddleware(
	rpcName string,
	streamName string,
	mw EmitMiddlewareFunc[T, any, any],
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.streamEmitMiddlewares[rpcName][streamName] = append(s.streamEmitMiddlewares[rpcName][streamName], mw)
	return s
}

// setGlobalStreamConfig sets the global configuration for streams.
func (s *internalServer[T]) setGlobalStreamConfig(cfg StreamConfig) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	if cfg.PingInterval <= 0 {
		cfg.PingInterval = 30 * time.Second
	}
	s.globalStreamConfig = cfg
	return s
}

// setRPCStreamConfig sets the configuration for streams within a specific RPC.
func (s *internalServer[T]) setRPCStreamConfig(rpcName string, cfg StreamConfig) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.rpcStreamConfigs[rpcName] = cfg
	return s
}

// setStreamConfig sets the configuration for a specific stream.
func (s *internalServer[T]) setStreamConfig(rpcName, streamName string, cfg StreamConfig) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.streamConfigs[rpcName][streamName] = cfg
	return s
}

// setGlobalErrorHandler sets the global error handler.
func (s *internalServer[T]) setGlobalErrorHandler(handler ErrorHandlerFunc[T]) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.globalErrorHandler = handler
	return s
}

// setRPCErrorHandler sets the error handler for a specific RPC.
func (s *internalServer[T]) setRPCErrorHandler(rpcName string, handler ErrorHandlerFunc[T]) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	s.rpcErrorHandlers[rpcName] = handler
	return s
}

// resolveErrorHandler returns the appropriate error handler for the given RPC name.
// Precedence: RPC > Global > Default (Passthrough)
func (s *internalServer[T]) resolveErrorHandler(rpcName string) ErrorHandlerFunc[T] {
	s.handlersMu.RLock()
	defer s.handlersMu.RUnlock()

	if handler, ok := s.rpcErrorHandlers[rpcName]; ok && handler != nil {
		return handler
	}
	if s.globalErrorHandler != nil {
		return s.globalErrorHandler
	}

	// Default: Passthrough
	return func(c *HandlerContext[T, any], err error) Error {
		return ToError(err)
	}
}

// setProcHandler registers the final implementation function and deserializer for the specified procedure name.
// The provided functions are stored as-is. Middlewares are composed at request time.
//
// Panics if a handler is already registered for the given procedure name.
func (s *internalServer[T]) setProcHandler(
	rpcName string,
	procName string,
	handler ProcHandlerFunc[T, any, any],
	deserializer DeserializerFunc,
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	if _, exists := s.procHandlers[rpcName][procName]; exists {
		panic(fmt.Sprintf("the procedure handler for %s.%s is already registered", rpcName, procName))
	}
	s.procHandlers[rpcName][procName] = handler
	s.procDeserializers[rpcName][procName] = deserializer
	return s
}

// setStreamHandler registers the final implementation function and deserializer for the specified stream name.
// The provided functions are stored as-is. Middlewares are composed at request time.
//
// Panics if a handler is already registered for the given stream name.
func (s *internalServer[T]) setStreamHandler(
	rpcName string,
	streamName string,
	handler StreamHandlerFunc[T, any, any],
	deserializer DeserializerFunc,
) *internalServer[T] {
	s.handlersMu.Lock()
	defer s.handlersMu.Unlock()
	if _, exists := s.streamHandlers[rpcName][streamName]; exists {
		panic(fmt.Sprintf("the stream handler for %s.%s is already registered", rpcName, streamName))
	}
	s.streamHandlers[rpcName][streamName] = handler
	s.streamDeserializers[rpcName][streamName] = deserializer
	return s
}

// handleRequest processes an incoming RPC request by parsing the request body,
// building the global middleware chain, and dispatching to the appropriate
// adapter (procedure or stream).
//
// The request body must contain a JSON object with the input data for the handler.
//
// Parameters:
//   - ctx: The request context
//   - props: The VDL context containing user-defined data
//   - rpcName: The name of the RPC service to invoke
//   - operationName: The name of the procedure or stream to invoke
//   - httpAdapter: The HTTP adapter for reading requests and writing responses
//
// Returns an error if request processing fails at the transport level.
func (s *internalServer[T]) handleRequest(
	ctx context.Context,
	props T,
	rpcName string,
	operationName string,
	httpAdapter HTTPAdapter,
) error {
	if httpAdapter == nil {
		return fmt.Errorf("the HTTP adapter is nil, please provide a valid adapter")
	}

	// Decode the request body into a json.RawMessage as the initial input container
	var rawInput json.RawMessage
	if err := json.NewDecoder(httpAdapter.RequestBody()).Decode(&rawInput); err != nil {
		res := Response[any]{
			Ok:    false,
			Error: Error{Message: "Invalid request body"},
		}
		return s.writeProcResponse(httpAdapter, res)
	}

	operation, operationExists := s.operationDefs[rpcName][operationName]
	if !operationExists {
		res := Response[any]{
			Ok:    false,
			Error: Error{Message: fmt.Sprintf("Invalid operation: %s.%s", rpcName, operationName)},
		}
		return s.writeProcResponse(httpAdapter, res)
	}

	// Build the unified handler context (raw input at this point).
	c := &HandlerContext[T, any]{
		Input:       rawInput,
		Props:       props,
		Context:     ctx,
		Annotations: cloneAnnotations(operation.Annotations),
		operation: OperationDefinition{
			RPCName:     operation.RPCName,
			Name:        operation.Name,
			Type:        operation.Type,
			Annotations: cloneAnnotations(operation.Annotations),
		},
	}

	// Handle Stream
	if operation.Type == OperationTypeStream {
		err := s.handleStreamRequest(c, rpcName, operationName, rawInput, httpAdapter)

		// If no error, return without sending any response
		if err == nil {
			return nil
		}

		// Send an event with the error before closing the connection
		errorHandler := s.resolveErrorHandler(rpcName)
		response := Response[any]{
			Ok:    false,
			Error: errorHandler(c, err),
		}

		jsonData, marshalErr := json.Marshal(response)
		if marshalErr != nil {
			return fmt.Errorf("failed to marshal stream error: %w", marshalErr)
		}
		resPayload := fmt.Sprintf("data: %s\n\n", jsonData)
		if _, writeErr := httpAdapter.Write([]byte(resPayload)); writeErr != nil {
			return writeErr
		}
		if flushErr := httpAdapter.Flush(); flushErr != nil {
			return flushErr
		}
	}

	// Handle Procedure
	output, err := s.handleProcRequest(c, rpcName, operationName, rawInput)
	response := Response[any]{}
	if err != nil {
		response.Ok = false
		errorHandler := s.resolveErrorHandler(rpcName)
		response.Error = errorHandler(c, err)
	} else {
		response.Ok = true
		response.Output = output
	}

	return s.writeProcResponse(httpAdapter, response)
}

// handleProcRequest builds the per-request middleware chain for a procedure and executes it.
// It returns the procedure output (as any) and an error if the handler failed.
func (s *internalServer[T]) handleProcRequest(
	c *HandlerContext[T, any],
	rpcName string,
	procName string,
	rawInput json.RawMessage,
) (any, error) {
	// Snapshot handler, middlewares, and deserializer under read lock
	s.handlersMu.RLock()
	baseHandler, ok := s.procHandlers[rpcName][procName]
	mws := s.procMiddlewares[rpcName][procName]
	rpcMws := s.rpcMiddlewares[rpcName]
	deserialize := s.procDeserializers[rpcName][procName]
	s.handlersMu.RUnlock()

	if !ok {
		return nil, fmt.Errorf("%s.%s procedure not implemented", rpcName, procName)
	}
	if deserialize == nil {
		return nil, fmt.Errorf("%s.%s procedure deserializer not registered", rpcName, procName)
	}

	// Deserialize, validate and transform input into its typed form
	typedInput, err := deserialize(rawInput)
	if err != nil {
		return nil, err
	}
	c.Input = typedInput

	// Compose specific per-proc middlewares around the base handler (reverse registration order)
	final := baseHandler
	if len(mws) > 0 {
		mwChain := append([]ProcMiddlewareFunc[T, any, any](nil), mws...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			final = mwChain[i](final)
		}
	}

	// Wrap the specific chain with RPC-level middlewares (executed before specific ones)
	exec := func(c *HandlerContext[T, any]) (any, error) { return final(c) }
	if len(rpcMws) > 0 {
		mwChain := append([]GlobalMiddlewareFunc[T](nil), rpcMws...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			exec = mwChain[i](exec)
		}
	}

	// Wrap the chain with global middlewares (executed before RPC-level ones)
	if len(s.globalMiddlewares) > 0 {
		mwChain := append([]GlobalMiddlewareFunc[T](nil), s.globalMiddlewares...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			exec = mwChain[i](exec)
		}
	}

	return exec(c)
}

// handleStreamRequest builds the per-request middleware chain for a stream, sets up SSE,
// composes emit middlewares, and executes the stream handler.
func (s *internalServer[T]) handleStreamRequest(
	c *HandlerContext[T, any],
	rpcName string,
	streamName string,
	rawInput json.RawMessage,
	httpAdapter HTTPAdapter,
) error {
	// Snapshot handler, middlewares, emit middlewares and deserializer under read lock
	s.handlersMu.RLock()
	baseHandler, ok := s.streamHandlers[rpcName][streamName]
	streamMws := s.streamMiddlewares[rpcName][streamName]
	emitMws := s.streamEmitMiddlewares[rpcName][streamName]
	rpcMws := s.rpcMiddlewares[rpcName]
	deserialize := s.streamDeserializers[rpcName][streamName]

	// Determine configuration (Precedence: Stream > RPC > Global)
	pingInterval := s.globalStreamConfig.PingInterval
	if cfg, ok := s.rpcStreamConfigs[rpcName]; ok && cfg.PingInterval > 0 {
		pingInterval = cfg.PingInterval
	}
	if cfg, ok := s.streamConfigs[rpcName][streamName]; ok && cfg.PingInterval > 0 {
		pingInterval = cfg.PingInterval
	}

	s.handlersMu.RUnlock()

	// Set SSE headers to the response
	httpAdapter.SetHeader("Content-Type", "text/event-stream")
	httpAdapter.SetHeader("Cache-Control", "no-cache")
	httpAdapter.SetHeader("Connection", "keep-alive")

	if !ok {
		return fmt.Errorf("%s.%s stream not implemented", rpcName, streamName)
	}
	if deserialize == nil {
		return fmt.Errorf("%s.%s stream deserializer not registered", rpcName, streamName)
	}

	// Deserialize, validate and transform input into its typed form
	typedInput, err := deserialize(rawInput)
	if err != nil {
		return err
	}
	c.Input = typedInput

	// We need to synchronize writes to the httpAdapter because pings run in a separate goroutine.
	// The closed flag prevents writes after the handler returns (when the response writer is invalid).
	var writeMu sync.Mutex
	var closed bool
	safeWrite := func(parts ...[]byte) error {
		writeMu.Lock()
		defer writeMu.Unlock()
		if closed {
			return nil
		}
		for _, part := range parts {
			if _, err := httpAdapter.Write(part); err != nil {
				return err
			}
		}
		return httpAdapter.Flush()
	}

	// Start Ping Loop, use a done channel to wait for goroutine exit before returning
	ctx, cancel := context.WithCancel(c.Context)
	pingDone := make(chan struct{})

	go func() {
		defer close(pingDone)
		ticker := time.NewTicker(pingInterval)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				_ = safeWrite([]byte(": ping\n\n"))
			}
		}
	}()

	// Ensure ping goroutine exits and mark response as closed before handler returns
	defer func() {
		cancel()
		<-pingDone
		writeMu.Lock()
		closed = true
		writeMu.Unlock()
	}()

	// Base emit writes SSE envelope with {ok:true, output}
	baseEmit := func(_ *HandlerContext[T, any], data any) error {
		response := Response[any]{
			Ok:     true,
			Output: data,
		}
		jsonData, err := json.Marshal(response)
		if err != nil {
			return fmt.Errorf("failed to marshal stream data: %w", err)
		}
		return safeWrite([]byte("data: "), jsonData, []byte("\n\n"))
	}

	// Compose emit middlewares (reverse registration order)
	emitFinal := baseEmit
	if len(emitMws) > 0 {
		mwChain := append([]EmitMiddlewareFunc[T, any, any](nil), emitMws...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			emitFinal = mwChain[i](emitFinal)
		}
	}

	// Compose stream middlewares around the base handler (reverse order)
	final := baseHandler
	if len(streamMws) > 0 {
		mwChain := append([]StreamMiddlewareFunc[T, any, any](nil), streamMws...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			final = mwChain[i](final)
		}
	}

	// Wrap the specific stream chain with RPC-level middlewares (executed before specific ones)
	exec := func(c *HandlerContext[T, any]) (any, error) { return nil, final(c, emitFinal) }
	if len(rpcMws) > 0 {
		mwChain := append([]GlobalMiddlewareFunc[T](nil), rpcMws...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			exec = mwChain[i](exec)
		}
	}

	// Wrap with global middlewares (executed before RPC-level ones)
	if len(s.globalMiddlewares) > 0 {
		mwChain := append([]GlobalMiddlewareFunc[T](nil), s.globalMiddlewares...)
		for i := len(mwChain) - 1; i >= 0; i-- {
			exec = mwChain[i](exec)
		}
	}

	_, err = exec(c)
	return err
}

// writeProcResponse writes a procedure response to the client as JSON.
// This helper method sets the appropriate Content-Type header and marshals
// the response data before sending it to the client.
//
// Parameters:
//   - httpAdapter: The HTTP adapter for writing the response
//   - response: The response data to send to the client
//
// Returns an error if writing the response fails.
func (s *internalServer[T]) writeProcResponse(
	httpAdapter HTTPAdapter,
	response Response[any],
) error {
	httpAdapter.SetHeader("Content-Type", "application/json")
	_, err := httpAdapter.Write(response.Bytes())
	if err != nil {
		return fmt.Errorf("failed to write response: %w", err)
	}
	return nil
}

// -----------------------------------------------------------------------------
// Server Implementation
// -----------------------------------------------------------------------------

// Server provides a high-level, type-safe API for building a VDL RPC server.
//
// It exposes:
//   - Procs: typed entries to register middlewares and the business handler per procedure
//   - Streams: typed entries to register middlewares, emit middlewares and the handler per stream
//   - Use: a global middleware API that runs for every operation (procedures and streams)
//
// The generic type parameter T is your application context (props) that flows through
// the entire request lifecycle (authentication, per-request data, dependencies, etc.).
type Server[T any] struct {
	intServer *internalServer[T]
	RPCs      *serverRPCRegistry[T]
}

// NewServer creates a new VDL RPC server instance ready to handle all
// defined procedures and streams using the middleware-based architecture.
//
// The generic type parameter T is your application context (props) that flows through
// the entire request lifecycle (authentication, per-request data, dependencies, etc.).
//
// Example:
//
//   type AppProps struct {
//       UserID string
//   }
//   s := NewServer[AppProps]()
func NewServer[T any]() *Server[T] {
	intServer := newInternalServer[T](VDLProcedures, VDLStreams)
	return &Server[T]{
		intServer: intServer,
		RPCs:      newServerRPCRegistry(intServer),
	}
}

// Use registers a global middleware that executes for every request (procedures and streams).
//
// Middlewares are executed in registration order and can:
//   - read/augment the HandlerContext
//   - short-circuit by returning an error
//   - call next to continue the chain
func (s *Server[T]) Use(mw GlobalMiddlewareFunc[T]) {
	s.intServer.addGlobalMiddleware(mw)
}

// SetStreamConfig sets the global configuration for all streams.
//
// This applies to all streams unless overridden by RPC-level or stream-specific configurations (if set).
func (s *Server[T]) SetStreamConfig(cfg StreamConfig) {
	s.intServer.setGlobalStreamConfig(cfg)
}

// SetErrorHandler sets a global error handler that intercepts and transforms errors
// from all RPCs before sending them to the client.
//
// This handler applies to all RPCs unless a specific handler is registered for an RPC.
func (s *Server[T]) SetErrorHandler(handler ErrorHandlerFunc[T]) {
	s.intServer.setGlobalErrorHandler(handler)
}

// HandleRequest processes an incoming RPC request and drives the complete
// request lifecycle (parsing, middleware chains, handler dispatch, response).
//
// rpcName and operationName must be extracted from the request URL (e.g. /rpc/MyService/GetUser -> "MyService", "GetUser").
//
// httpAdapter bridges VDL RPC with your HTTP framework (use NewNetHTTPAdapter for net/http or compatible).
//
// Example (net/http):
//
//   http.HandleFunc("POST /rpc/{rpcName}/{operationName}", func(w http.ResponseWriter, r *http.Request) {
//       ctx := r.Context()
//       props := AppProps{UserID: "abc"}
//       adapter := NewNetHTTPAdapter(w, r)
//       _ = server.HandleRequest(ctx, props, r.PathValue("rpcName"), r.PathValue("operationName"), adapter)
//   })
func (s *Server[T]) HandleRequest(ctx context.Context, props T, rpcName string, operationName string, httpAdapter HTTPAdapter) error {
	return s.intServer.handleRequest(ctx, props, rpcName, operationName, httpAdapter)
}

// serverRPCRegistry provides typed access to register handlers and middlewares for procedures and streams within a specific RPC service.
type serverRPCRegistry[T any] struct {
	intServer *internalServer[T]
}

// newServerRPCRegistry creates a new serverRPCRegistry for the given internal server instance.
func newServerRPCRegistry[T any](intServer *internalServer[T]) *serverRPCRegistry[T] {
	return &serverRPCRegistry[T]{intServer: intServer}
}

// Database returns the server registry for the Database RPC service.
func (r *serverRPCRegistry[T]) Database() *serverDatabaseRPC[T] {
	return &serverDatabaseRPC[T]{
		intServer: r.intServer,
		Procs:     &serverDatabaseProcs[T]{intServer: r.intServer},
		Streams:   &serverDatabaseStreams[T]{intServer: r.intServer},
	}
}

// serverDatabaseRPC groups the generated server registration APIs for the Database RPC service.
type serverDatabaseRPC[T any] struct {
	intServer *internalServer[T]
	Procs     *serverDatabaseProcs[T]
	Streams   *serverDatabaseStreams[T]
}

// Use registers middleware that runs for every request inside the Database RPC service.
func (r *serverDatabaseRPC[T]) Use(mw GlobalMiddlewareFunc[T]) {
	r.intServer.addRPCMiddleware("Database", mw)
}

// SetStreamConfig sets the default stream configuration for the Database RPC service.
func (r *serverDatabaseRPC[T]) SetStreamConfig(cfg StreamConfig) {
	r.intServer.setRPCStreamConfig("Database", cfg)
}

// SetErrorHandler sets the error handler for the Database RPC service.
func (r *serverDatabaseRPC[T]) SetErrorHandler(handler ErrorHandlerFunc[T]) {
	r.intServer.setRPCErrorHandler("Database", handler)
}

// serverDatabaseProcs exposes the generated procedure registration APIs for the Database RPC service.
type serverDatabaseProcs[T any] struct {
	intServer *internalServer[T]
}

// serverDatabaseStreams exposes the generated stream registration APIs for the Database RPC service.
type serverDatabaseStreams[T any] struct {
	intServer *internalServer[T]
}

// Query returns the registration entry for the Database.query procedure.
//
// Executes one or more SQL queries against the database.
//
// Queries are executed in order and each query returns one result item.
// Empty or failed queries are returned as result items with type "error".
func (r *serverDatabaseProcs[T]) Query() procDatabaseQueryEntry[T] {
	return procDatabaseQueryEntry[T]{intServer: r.intServer}
}

// procDatabaseQueryEntry contains the generated registration API for the Database.query procedure.
type procDatabaseQueryEntry[T any] struct {
	intServer *internalServer[T]
}

// DatabaseQueryHandlerContext is the typed handler context passed to Database.query procedure handlers.
type DatabaseQueryHandlerContext[T any] = HandlerContext[T, DatabaseQueryInput]

// DatabaseQueryHandlerFunc is the typed handler signature for the Database.query procedure.
type DatabaseQueryHandlerFunc[T any] func(c *DatabaseQueryHandlerContext[T]) (DatabaseQueryOutput, error)

// DatabaseQueryMiddlewareFunc is the typed middleware signature for the Database.query procedure.
type DatabaseQueryMiddlewareFunc[T any] func(next DatabaseQueryHandlerFunc[T]) DatabaseQueryHandlerFunc[T]

// Use registers typed middleware for the Database.query procedure.
func (e procDatabaseQueryEntry[T]) Use(mw DatabaseQueryMiddlewareFunc[T]) {
	adapted := func(next ProcHandlerFunc[T, any, any]) ProcHandlerFunc[T, any, any] {
		return func(cGeneric *HandlerContext[T, any]) (any, error) {
			typedNext := func(c *DatabaseQueryHandlerContext[T]) (DatabaseQueryOutput, error) {
				cGeneric.Props = c.Props
				cGeneric.Input = c.Input
				cGeneric.Annotations = cloneAnnotations(c.Annotations)
				genericOutput, err := next(cGeneric)
				if err != nil {
					return DatabaseQueryOutput{}, err
				}
				typedOutput, _ := genericOutput.(DatabaseQueryOutput)
				return typedOutput, nil
			}
			typedChain := mw(typedNext)
			typedInput, _ := cGeneric.Input.(DatabaseQueryInput)
			cSpecific := &DatabaseQueryHandlerContext[T]{
				Props:       cGeneric.Props,
				Input:       typedInput,
				Context:     cGeneric.Context,
				Annotations: cloneAnnotations(cGeneric.Annotations),
				operation:   cGeneric.operation,
			}
			return typedChain(cSpecific)
		}
	}
	e.intServer.addProcMiddleware("Database", "query", adapted)
}

// Handle registers the typed business handler for the Database.query procedure.
func (e procDatabaseQueryEntry[T]) Handle(handler DatabaseQueryHandlerFunc[T]) {
	adaptedHandler := func(cGeneric *HandlerContext[T, any]) (any, error) {
		typedInput, _ := cGeneric.Input.(DatabaseQueryInput)
		cSpecific := &DatabaseQueryHandlerContext[T]{
			Props:       cGeneric.Props,
			Input:       typedInput,
			Context:     cGeneric.Context,
			Annotations: cloneAnnotations(cGeneric.Annotations),
			operation:   cGeneric.operation,
		}
		return handler(cSpecific)
	}
	deserializer := func(raw json.RawMessage) (any, error) {
		var input DatabaseQueryInput
		if err := json.Unmarshal(raw, &input); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Database.query input: %w", err)
		}
		return input, nil
	}
	e.intServer.setProcHandler("Database", "query", adaptedHandler, deserializer)
}

// System returns the server registry for the System RPC service.
func (r *serverRPCRegistry[T]) System() *serverSystemRPC[T] {
	return &serverSystemRPC[T]{
		intServer: r.intServer,
		Procs:     &serverSystemProcs[T]{intServer: r.intServer},
		Streams:   &serverSystemStreams[T]{intServer: r.intServer},
	}
}

// serverSystemRPC groups the generated server registration APIs for the System RPC service.
type serverSystemRPC[T any] struct {
	intServer *internalServer[T]
	Procs     *serverSystemProcs[T]
	Streams   *serverSystemStreams[T]
}

// Use registers middleware that runs for every request inside the System RPC service.
func (r *serverSystemRPC[T]) Use(mw GlobalMiddlewareFunc[T]) {
	r.intServer.addRPCMiddleware("System", mw)
}

// SetStreamConfig sets the default stream configuration for the System RPC service.
func (r *serverSystemRPC[T]) SetStreamConfig(cfg StreamConfig) {
	r.intServer.setRPCStreamConfig("System", cfg)
}

// SetErrorHandler sets the error handler for the System RPC service.
func (r *serverSystemRPC[T]) SetErrorHandler(handler ErrorHandlerFunc[T]) {
	r.intServer.setRPCErrorHandler("System", handler)
}

// serverSystemProcs exposes the generated procedure registration APIs for the System RPC service.
type serverSystemProcs[T any] struct {
	intServer *internalServer[T]
}

// serverSystemStreams exposes the generated stream registration APIs for the System RPC service.
type serverSystemStreams[T any] struct {
	intServer *internalServer[T]
}

// Health returns the registration entry for the System.health procedure.
//
// Checks whether the server can perform a basic database read.
func (r *serverSystemProcs[T]) Health() procSystemHealthEntry[T] {
	return procSystemHealthEntry[T]{intServer: r.intServer}
}

// procSystemHealthEntry contains the generated registration API for the System.health procedure.
type procSystemHealthEntry[T any] struct {
	intServer *internalServer[T]
}

// SystemHealthHandlerContext is the typed handler context passed to System.health procedure handlers.
type SystemHealthHandlerContext[T any] = HandlerContext[T, Void]

// SystemHealthHandlerFunc is the typed handler signature for the System.health procedure.
type SystemHealthHandlerFunc[T any] func(c *SystemHealthHandlerContext[T]) (SystemHealthOutput, error)

// SystemHealthMiddlewareFunc is the typed middleware signature for the System.health procedure.
type SystemHealthMiddlewareFunc[T any] func(next SystemHealthHandlerFunc[T]) SystemHealthHandlerFunc[T]

// Use registers typed middleware for the System.health procedure.
func (e procSystemHealthEntry[T]) Use(mw SystemHealthMiddlewareFunc[T]) {
	adapted := func(next ProcHandlerFunc[T, any, any]) ProcHandlerFunc[T, any, any] {
		return func(cGeneric *HandlerContext[T, any]) (any, error) {
			typedNext := func(c *SystemHealthHandlerContext[T]) (SystemHealthOutput, error) {
				cGeneric.Props = c.Props
				cGeneric.Input = c.Input
				cGeneric.Annotations = cloneAnnotations(c.Annotations)
				genericOutput, err := next(cGeneric)
				if err != nil {
					return SystemHealthOutput{}, err
				}
				typedOutput, _ := genericOutput.(SystemHealthOutput)
				return typedOutput, nil
			}
			typedChain := mw(typedNext)
			typedInput, _ := cGeneric.Input.(Void)
			cSpecific := &SystemHealthHandlerContext[T]{
				Props:       cGeneric.Props,
				Input:       typedInput,
				Context:     cGeneric.Context,
				Annotations: cloneAnnotations(cGeneric.Annotations),
				operation:   cGeneric.operation,
			}
			return typedChain(cSpecific)
		}
	}
	e.intServer.addProcMiddleware("System", "health", adapted)
}

// Handle registers the typed business handler for the System.health procedure.
func (e procSystemHealthEntry[T]) Handle(handler SystemHealthHandlerFunc[T]) {
	adaptedHandler := func(cGeneric *HandlerContext[T, any]) (any, error) {
		typedInput, _ := cGeneric.Input.(Void)
		cSpecific := &SystemHealthHandlerContext[T]{
			Props:       cGeneric.Props,
			Input:       typedInput,
			Context:     cGeneric.Context,
			Annotations: cloneAnnotations(cGeneric.Annotations),
			operation:   cGeneric.operation,
		}
		return handler(cSpecific)
	}
	deserializer := func(raw json.RawMessage) (any, error) {
		return Void{}, nil
	}
	e.intServer.setProcHandler("System", "health", adaptedHandler, deserializer)
}

// Session returns the registration entry for the System.session procedure.
//
// Returns the authentication role for the current session.
func (r *serverSystemProcs[T]) Session() procSystemSessionEntry[T] {
	return procSystemSessionEntry[T]{intServer: r.intServer}
}

// procSystemSessionEntry contains the generated registration API for the System.session procedure.
type procSystemSessionEntry[T any] struct {
	intServer *internalServer[T]
}

// SystemSessionHandlerContext is the typed handler context passed to System.session procedure handlers.
type SystemSessionHandlerContext[T any] = HandlerContext[T, Void]

// SystemSessionHandlerFunc is the typed handler signature for the System.session procedure.
type SystemSessionHandlerFunc[T any] func(c *SystemSessionHandlerContext[T]) (SystemSessionOutput, error)

// SystemSessionMiddlewareFunc is the typed middleware signature for the System.session procedure.
type SystemSessionMiddlewareFunc[T any] func(next SystemSessionHandlerFunc[T]) SystemSessionHandlerFunc[T]

// Use registers typed middleware for the System.session procedure.
func (e procSystemSessionEntry[T]) Use(mw SystemSessionMiddlewareFunc[T]) {
	adapted := func(next ProcHandlerFunc[T, any, any]) ProcHandlerFunc[T, any, any] {
		return func(cGeneric *HandlerContext[T, any]) (any, error) {
			typedNext := func(c *SystemSessionHandlerContext[T]) (SystemSessionOutput, error) {
				cGeneric.Props = c.Props
				cGeneric.Input = c.Input
				cGeneric.Annotations = cloneAnnotations(c.Annotations)
				genericOutput, err := next(cGeneric)
				if err != nil {
					return SystemSessionOutput{}, err
				}
				typedOutput, _ := genericOutput.(SystemSessionOutput)
				return typedOutput, nil
			}
			typedChain := mw(typedNext)
			typedInput, _ := cGeneric.Input.(Void)
			cSpecific := &SystemSessionHandlerContext[T]{
				Props:       cGeneric.Props,
				Input:       typedInput,
				Context:     cGeneric.Context,
				Annotations: cloneAnnotations(cGeneric.Annotations),
				operation:   cGeneric.operation,
			}
			return typedChain(cSpecific)
		}
	}
	e.intServer.addProcMiddleware("System", "session", adapted)
}

// Handle registers the typed business handler for the System.session procedure.
func (e procSystemSessionEntry[T]) Handle(handler SystemSessionHandlerFunc[T]) {
	adaptedHandler := func(cGeneric *HandlerContext[T, any]) (any, error) {
		typedInput, _ := cGeneric.Input.(Void)
		cSpecific := &SystemSessionHandlerContext[T]{
			Props:       cGeneric.Props,
			Input:       typedInput,
			Context:     cGeneric.Context,
			Annotations: cloneAnnotations(cGeneric.Annotations),
			operation:   cGeneric.operation,
		}
		return handler(cSpecific)
	}
	deserializer := func(raw json.RawMessage) (any, error) {
		return Void{}, nil
	}
	e.intServer.setProcHandler("System", "session", adaptedHandler, deserializer)
}

// Status returns the registration entry for the System.status procedure.
//
// Returns server information and runtime statistics.
func (r *serverSystemProcs[T]) Status() procSystemStatusEntry[T] {
	return procSystemStatusEntry[T]{intServer: r.intServer}
}

// procSystemStatusEntry contains the generated registration API for the System.status procedure.
type procSystemStatusEntry[T any] struct {
	intServer *internalServer[T]
}

// SystemStatusHandlerContext is the typed handler context passed to System.status procedure handlers.
type SystemStatusHandlerContext[T any] = HandlerContext[T, Void]

// SystemStatusHandlerFunc is the typed handler signature for the System.status procedure.
type SystemStatusHandlerFunc[T any] func(c *SystemStatusHandlerContext[T]) (SystemStatusOutput, error)

// SystemStatusMiddlewareFunc is the typed middleware signature for the System.status procedure.
type SystemStatusMiddlewareFunc[T any] func(next SystemStatusHandlerFunc[T]) SystemStatusHandlerFunc[T]

// Use registers typed middleware for the System.status procedure.
func (e procSystemStatusEntry[T]) Use(mw SystemStatusMiddlewareFunc[T]) {
	adapted := func(next ProcHandlerFunc[T, any, any]) ProcHandlerFunc[T, any, any] {
		return func(cGeneric *HandlerContext[T, any]) (any, error) {
			typedNext := func(c *SystemStatusHandlerContext[T]) (SystemStatusOutput, error) {
				cGeneric.Props = c.Props
				cGeneric.Input = c.Input
				cGeneric.Annotations = cloneAnnotations(c.Annotations)
				genericOutput, err := next(cGeneric)
				if err != nil {
					return SystemStatusOutput{}, err
				}
				typedOutput, _ := genericOutput.(SystemStatusOutput)
				return typedOutput, nil
			}
			typedChain := mw(typedNext)
			typedInput, _ := cGeneric.Input.(Void)
			cSpecific := &SystemStatusHandlerContext[T]{
				Props:       cGeneric.Props,
				Input:       typedInput,
				Context:     cGeneric.Context,
				Annotations: cloneAnnotations(cGeneric.Annotations),
				operation:   cGeneric.operation,
			}
			return typedChain(cSpecific)
		}
	}
	e.intServer.addProcMiddleware("System", "status", adapted)
}

// Handle registers the typed business handler for the System.status procedure.
func (e procSystemStatusEntry[T]) Handle(handler SystemStatusHandlerFunc[T]) {
	adaptedHandler := func(cGeneric *HandlerContext[T, any]) (any, error) {
		typedInput, _ := cGeneric.Input.(Void)
		cSpecific := &SystemStatusHandlerContext[T]{
			Props:       cGeneric.Props,
			Input:       typedInput,
			Context:     cGeneric.Context,
			Annotations: cloneAnnotations(cGeneric.Annotations),
			operation:   cGeneric.operation,
		}
		return handler(cSpecific)
	}
	deserializer := func(raw json.RawMessage) (any, error) {
		return Void{}, nil
	}
	e.intServer.setProcHandler("System", "status", adaptedHandler, deserializer)
}
