name: Benchmark NSQLite and other drivers
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  benchmark:
    name: Benchmark NSQLite and other drivers
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .ssh directory exists even if it's empty
        run: mkdir -p /home/runner/.ssh

      - name: Run Benchmark
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            task install
            nsqlitebench --ci
