name: Lint, test, build and benchmark
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  lint-and-test:
    name: Lint, test, build and benchmark the code
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .ssh directory exists even if it's empty
        run: mkdir -p /home/runner/.ssh

      - name: Run lint, test, build and benchmark
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            task lint
            task test
            task build
            task install
            nsqlitebench --ci
